### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by LunaSare** [LunaSare/datelife_paper1#1]
Steps for writing a paper. Slightly modified from https://twitter.com/SarahKnutie/status/1084484089833578497

- [x] 1. Add line/page numbers to doc, headers for each section, authors/affiliations, working title, acknowledgements. Start thinking about which journal you will be submitting the manuscript to. Name file
 - [x] 2. Write the last paragraph of the introduction, which includes the goals/objectives/predictions. This step is important to determine which methods/results to include. Outline methods.
 - [x] 3. Write out methods.
 - [x] 4. Re-read and revise intro paragraph/methods.
 - [x] 5. Outline the tests that you will be performing with specific analyses in the results section.
 - [x] 6. Perform stats & put a link to the code and outputs into the availability section, this will help while writing out the results. Add figures below each test to visualize the results.
 - [x] 7. Write results & decide which figs/tables to include.
 - [x] 8. Re-read and revise the results.
 - [x] 9. Write very rough outline of introduction.
 - [x] 10. Re-read the pub lit (& find new papers). Outline main results for each paper. Decide on which cites to include & add them to the outline.
 - [x] 11. Add text to outline of intro.
 - [x] 12. Outline and write the first paragraph of the discussion. Roughly outline the rest of the discussion.
 - [x] 13. Go back and forth between writing out the introduction and discussion (based on motivation for that day).
 - [x] 14. Finish introduction.
 - [x] 15. Re-read introduction.
 - [x] 16. Finish discussion.
 - [x] 17. Re-read discussion.
 - [x] 18. Outline the abstract then write it out. 
 - [x] 19. Read the full manuscript.
 - [ ]  20. Have someone else (or coauthors) read the manuscript.
 - [ ]  21. Incorporate comments and read the final manuscript.
 - [ ]  22. Submit.
